export const ORDER_PLACED_STATUS = 'PLACED';
export const ORDER_SHIPPED_STATUS = 'SHIPPED';
export const ORDER_OUT_FOR_DELIVERY_STATUS = 'OUT_FOR_DELIVERY';
export const ORDER_DELIVERED_STATUS = 'DELIVERED';
export const ORDER_CANCELLED_STATUS = 'CANCELLED';
